In [1]:
import pandas as pd

llm_scores = pd.read_csv('llm_scores.csv')

llm_scores.head()

/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.4' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,Query,Verse,Psalm Num,HumanScore,Method,Similarity Score (%),Text,LLM Score 1,Unnamed: 8
0,Create in me a clean heart,1For the End concerning things that shall be c...,79,NaN,TF-IDF + GloVe,16.00,Bible,3.0,NaN
1,Create in me a clean heart,1An ode of ascents Ilift my eyes to You Whodwe...,122,NaN,TF-IDF + GloVe,13.98,Bible,3.0,NaN
2,Create in me a clean heart,1For the End corrupt not by David for a pillar...,56,NaN,TF-IDF + GloVe,13.46,Bible,3.0,NaN
3,Create in me a clean heart,An ode of ascents To the Lord in my affliction...,119,NaN,TF-IDF + GloVe,13.11,Bible,3.0,NaN
4,Create in me a clean heart,For the End concerning the eighth a psalm by D...,11,NaN,TF-IDF + GloVe,12.74,Bible,3.0,NaN

In [30]:
old_scores_llm = pd.read_csv('results_scored_old.csv')

old_scores_llm.head()

,Query,Method,Similarity Score (%),Text,Psalm Num,Verse,CadenScore,LLM Score 1
0,Create in me a clean heart,TFIDF_GLoVe,26.10,Psalter,100.0,I will sing of mercy and judgment unto Thee O ...,9.0,3.0
1,Create in me a clean heart,TFIDF_GLoVe,25.67,Bible,4.0,For the End in psalms an ode by David You hear...,6.0,3.0
2,Create in me a clean heart,TFIDF_GLoVe,21.90,Bible,31.0,By David concerning understanding Blessed are ...,3.0,3.0
3,Create in me a clean heart,TFIDF_GLoVe,18.33,Psalter,31.0,Blessed are they whose iniquities are forgiven...,10.0,3.0
4,Create in me a clean heart,TFIDF_GLoVe,18.12,Bible,61.0,For the End for Jeduthun a psalm by David Shal...,7.0,3.0

In [19]:
caden = pd.read_csv("../results_scored.csv")

caden = caden.drop(columns=['HumanScore_x', 'HumanScore_y'])

caden.head()

,Query,Method,Similarity Score (%),Text,Psalm Num,Verse,HumanScore
0,For the Peace of the world,TFIDF_GLoVe,43.73,Bible,92,1For the day before the Sabbath when the earth...,10.0
1,For the Peace of the world,TFIDF_GLoVe,41.00,Psalter,121,"I was glad because of them that said to me, Le...",0.0
2,For the Peace of the world,TFIDF_GLoVe,40.99,Bible,121,1An ode of ascents Iwas glad when they said to...,8.0
3,For the Peace of the world,TFIDF_GLoVe,38.74,Bible,131,1An ode of ascents Remember David O Lord And a...,4.0
4,For the Peace of the world,TFIDF_GLoVe,38.43,Bible,96,By David when His earth is restored The Lord r...,9.0

In [8]:
print(f"Caden's Queries \n {caden['Query'].unique()}")

Caden's Queries
 <ArrowStringArray>
[                                                                                                                                                                                                                'For the Peace of the world',
                                                                                                                                                                                                                                      'mercy',
                                                                                                                                                                                                                    'The Lord is my shepherd',
                                                                                                                                                                                                                    'protection from enemies',
                                                                                                                                                                                                               'praise in times of suffering',
                                                                                                                                                       'How does the psalmist express trust in God while surrounded by fear and uncertainty?',
                                                                                                                                           'Verses where the psalmist remembers past deliverance and uses it to find hope in present trials.',
 'Rejoice, O ye heavens, sound the trumpets, ye foundation of the earth, thunder forth gladness, O ye mountains: for behold, Emmanuel to the Cross our sins, and the Giver of Life hath slain death, raising up Adam; for He loveth mankind.',
                                                                                               'Have mercy on me, O God, have mercy on me. For my soul trusts in Thee, and in the shadow of Thy wings will I hope, until iniquity pass away.',
                                                                                                                                                                                                                 'for the peace of the world',
                                                                                                                                                                                                                 'Create in me a clean heart',
                                                                                                                                                                                                                                     'prayer']
Length: 12, dtype: str

In [12]:
unique_queries_df = pd.DataFrame(
    caden['Query'].unique(),
    columns=['Query']
)

unique_queries_df

                                                Query
0                          For the Peace of the world
1                                               mercy
2                             The Lord is my shepherd
3                             protection from enemies
4                        praise in times of suffering
5   How does the psalmist express trust in God whi...
6   Verses where the psalmist remembers past deliv...
7   Rejoice, O ye heavens, sound the trumpets, ye ...
8   Have mercy on me, O God, have mercy on me. For...
9                          for the peace of the world
10                         Create in me a clean heart
11                                             prayer

In [14]:
llm_unique_queries_df = pd.DataFrame(
    llm_scores['Query'].unique(),
    columns=['Query']
)

llm_unique_queries_df

                                                Query
0                          Create in me a clean heart
1                          For the Peace of the world
2   Have mercy on me, O God, have mercy on me. For...
3   How does the psalmist express trust in God whi...
4                                               mercy
5                        praise in times of suffering
6                                              prayer
7                             protection from enemies
8   Rejoice, O ye heavens, sound the trumpets, ye ...
9                             The Lord is my shepherd
10  Verses where the psalmist remembers past deliv...
11  Lord, now lettest thou thy servant depart in p...
12  O Lord God of my salvation, I have cried day a...
13  God is the Lord, which has shewed us light. Bl...
14  When the stone had been sealed by the Jews; wh...
15  The Choir of the Saints have found the fountai...
16  Be thou exalted, O bridegroom, like unto Abrah...
17                                         Forgivness
18                                               Love
19                                            Belief
20                                      Transgression
21                                   Love for Mankind
22  “Psalms that contrast human mortality with div...
23  “Which psalms use parallelism heavily to empha...
24  “Compare psalms that emphasize divine wrath ve...
25  Psalms containing repeated rhetorical question...
26  Find psalms describing repentance after sin, e...
27  “Find psalms that include both crying out for ...
28  “Psalms that express deep lament and trust in ...
29  Psalms that express a transition from deep per...
30  Find psalms that describe God as a refuge and ...
31  Which psalms focus on repentance and moral fai...
32  Psalms that reflect on human mortality and the...
33  Identify psalms that combine themes of sufferi...
34   Psalms that move from lament and despair to p...
35  Psalms describing God as a refuge and protecto...
36                          Attend to my supplication
37                              Harken unto my prayer
38                     For His mercy endureth forever
39                        Lord I have cried unto thee
40                                   Have Mercy on me
41                                   God with with us
42  The Lord is my helper; I will not fear what ma...
43                                       Deliverance
44                                            Refuge
45                                           creation
46                                                law
47  Blessed is God, who illuminate and sanctifieth...
48  Identify psalms that celebrate God's sovereign...
49  Find psalms that portray God as both a righteo...

In [17]:
common_queries = pd.merge(unique_queries_df, llm_unique_queries_df, on='Query')
common_queries

                                                Query
0                          For the Peace of the world
1                                               mercy
2                             The Lord is my shepherd
3                             protection from enemies
4                        praise in times of suffering
5   How does the psalmist express trust in God whi...
6   Verses where the psalmist remembers past deliv...
7   Rejoice, O ye heavens, sound the trumpets, ye ...
8   Have mercy on me, O God, have mercy on me. For...
9                          Create in me a clean heart
10                                             prayer

In [27]:
common_scores = pd.merge(llm_scores, caden, on=['Query', 'Text', 'Psalm Num', 'Verse', 'Method', 'Similarity Score (%)'])

common_scores

,Query,Verse,Psalm Num,HumanScore_x,Method,Similarity Score (%),Text,LLM Score 1,Unnamed: 8,HumanScore_y
0,Create in me a clean heart,For the End a psalm by David The heavens decla...,18,NaN,BERT,69.89,Bible,3.0,NaN,4.0
1,Create in me a clean heart,Alleluia of Aggeus and Zacharias Praise the Lo...,147,NaN,BERT,68.31,Bible,3.0,NaN,5.0
2,prayer,For the End a psalm by David The heavens decla...,18,NaN,BERT,43.82,Bible,3.0,NaN,1.0
3,Create in me a clean heart,"Judge Thou, O Lord, them that do me injustice;...",34,NaN,BERT,69.06,Psalter,3.0,NaN,8.0
4,Create in me a clean heart,"The God of gods, even the Lord, hath spoken, a...",49,NaN,BERT,68.69,Psalter,3.0,NaN,5.0
5,Create in me a clean heart,"We have heard with our ears, O God, for our fa...",43,NaN,BERT,68.66,Psalter,3.0,NaN,0.0
6,prayer,"Judge Thou, O Lord, them that do me injustice;...",34,NaN,BERT,40.30,Psalter,3.0,NaN,3.0
7,prayer,"Judge me, God, and give judgment in my cause a...",42,NaN,BERT,39.39,Psalter,3.0,NaN,6.0
8,prayer,"Sing unto the Lord a new song, His praise is i...",149,NaN,BERT,38.91,Psalter,3.0,NaN,8.0
9,prayer,"Save me, O God, by Thy name, and judge me by T...",53,NaN,BERT,38.70,Psalter,3.0,NaN,10.0

In [28]:
common_scores['scaledHuman'] = (common_scores['HumanScore_y']*3 / 10).round().astype(int)

common_scores

,Query,Verse,Psalm Num,HumanScore_x,Method,Similarity Score (%),Text,LLM Score 1,Unnamed: 8,HumanScore_y,scaledHuman
0,Create in me a clean heart,For the End a psalm by David The heavens decla...,18,NaN,BERT,69.89,Bible,3.0,NaN,4.0,1
1,Create in me a clean heart,Alleluia of Aggeus and Zacharias Praise the Lo...,147,NaN,BERT,68.31,Bible,3.0,NaN,5.0,2
2,prayer,For the End a psalm by David The heavens decla...,18,NaN,BERT,43.82,Bible,3.0,NaN,1.0,0
3,Create in me a clean heart,"Judge Thou, O Lord, them that do me injustice;...",34,NaN,BERT,69.06,Psalter,3.0,NaN,8.0,2
4,Create in me a clean heart,"The God of gods, even the Lord, hath spoken, a...",49,NaN,BERT,68.69,Psalter,3.0,NaN,5.0,2
5,Create in me a clean heart,"We have heard with our ears, O God, for our fa...",43,NaN,BERT,68.66,Psalter,3.0,NaN,0.0,0
6,prayer,"Judge Thou, O Lord, them that do me injustice;...",34,NaN,BERT,40.30,Psalter,3.0,NaN,3.0,1
7,prayer,"Judge me, God, and give judgment in my cause a...",42,NaN,BERT,39.39,Psalter,3.0,NaN,6.0,2
8,prayer,"Sing unto the Lord a new song, His praise is i...",149,NaN,BERT,38.91,Psalter,3.0,NaN,8.0,2
9,prayer,"Save me, O God, by Thy name, and judge me by T...",53,NaN,BERT,38.70,Psalter,3.0,NaN,10.0,3

In [25]:
common_scores.shape

(10, 11)

In [31]:
old_scores_llm.head()

,Query,Method,Similarity Score (%),Text,Psalm Num,Verse,CadenScore,LLM Score 1
0,Create in me a clean heart,TFIDF_GLoVe,26.10,Psalter,100.0,I will sing of mercy and judgment unto Thee O ...,9.0,3.0
1,Create in me a clean heart,TFIDF_GLoVe,25.67,Bible,4.0,For the End in psalms an ode by David You hear...,6.0,3.0
2,Create in me a clean heart,TFIDF_GLoVe,21.90,Bible,31.0,By David concerning understanding Blessed are ...,3.0,3.0
3,Create in me a clean heart,TFIDF_GLoVe,18.33,Psalter,31.0,Blessed are they whose iniquities are forgiven...,10.0,3.0
4,Create in me a clean heart,TFIDF_GLoVe,18.12,Bible,61.0,For the End for Jeduthun a psalm by David Shal...,7.0,3.0

In [33]:
old_scores_llm = old_scores_llm.dropna(subset=['CadenScore'])

old_scores_llm['CadenScore_scaled'] = (
    old_scores_llm['CadenScore'] * 3 / 10
).round().astype(int)

old_scores_llm.head()

,Query,Method,Similarity Score (%),Text,Psalm Num,Verse,CadenScore,LLM Score 1,CadenScore_scaled
0,Create in me a clean heart,TFIDF_GLoVe,26.10,Psalter,100.0,I will sing of mercy and judgment unto Thee O ...,9.0,3.0,3
1,Create in me a clean heart,TFIDF_GLoVe,25.67,Bible,4.0,For the End in psalms an ode by David You hear...,6.0,3.0,2
2,Create in me a clean heart,TFIDF_GLoVe,21.90,Bible,31.0,By David concerning understanding Blessed are ...,3.0,3.0,1
3,Create in me a clean heart,TFIDF_GLoVe,18.33,Psalter,31.0,Blessed are they whose iniquities are forgiven...,10.0,3.0,3
4,Create in me a clean heart,TFIDF_GLoVe,18.12,Bible,61.0,For the End for Jeduthun a psalm by David Shal...,7.0,3.0,2

In [38]:
old_scores_llm['CadenScore_scaled'].value_counts()

CadenScore_scaled
2    87
3    68
1    57
0    25
Name: count, dtype: int64

In [39]:
old_scores_llm['LLM Score 1'].value_counts()

LLM Score 1
3.0    172
2.0     62
0.0      2
1.0      1
Name: count, dtype: int64

In [41]:
comparison_df = pd.concat(
    [
        old_scores_llm['CadenScore_scaled'].value_counts().sort_index(),
        old_scores_llm['LLM Score 1'].value_counts().sort_index()
    ],
    axis=1
)

comparison_df.columns = ['CadenScore_scaled', 'LLM Score 1']

comparison_df

   CadenScore_scaled  LLM Score 1
0                 25            2
1                 57            1
2                 87           62
3                 68          172

In [42]:
from sklearn.metrics import cohen_kappa_score

 cohen_kappa_score(
    old_scores_llm['CadenScore_scaled'],
    old_scores_llm['LLM Score 1'],
    weights='quadratic'
)

print(kappa)

0.058490773286467346

In [43]:
old_scores_llm['CadenScore'].describe()

count    237.000000
mean       6.025424
std        3.066942
min        0.000000
25%        3.000000
50%        7.000000
75%        9.000000
max       10.000000
Name: CadenScore, dtype: float64

In [44]:
old_scores_llm['CadenScore_scaled'].value_counts(normalize=True).sort_index()

CadenScore_scaled
0    0.105485
1    0.240506
2    0.367089
3    0.286920
Name: proportion, dtype: float64

In [45]:
pd.crosstab(
    old_scores_llm['CadenScore_scaled'],
    old_scores_llm['LLM Score 1'],
    normalize='index'
)

LLM Score 1             0.0       1.0       2.0       3.0
CadenScore_scaled
0                  0.040000  0.000000  0.240000  0.720000
1                  0.017544  0.017544  0.298246  0.666667
2                  0.000000  0.000000  0.275862  0.724138
3                  0.000000  0.000000  0.220588  0.779412