In [50]:
import pandas as pd

psalms = pd.read_csv("cleaned_psalm_verses.csv")
psalms

,tradition,text,psalm_num,verse_num,verse
0,Orthodox,Bible,1,1,Blessed is the man Who walks not in the counse...
1,Orthodox,Bible,1,2,But his will is in the law of the Lord And in ...
2,Orthodox,Bible,1,3,He shall be like a tree Planted by streams of ...
3,Orthodox,Bible,1,4,Not so are the ungodly not so But they are lik...
4,Orthodox,Bible,1,5,Therefore the ungodly shall not rise in the ju...
...,...,...,...,...,...
4937,Orthodox,Psalter,150,1,Praise God in His holy ones; praise Him in the...
4938,Orthodox,Psalter,150,2,Praise Him for His mighty acts; praise Him acc...
4939,Orthodox,Psalter,150,3,Praise Him with the sound of the trumpet; prai...
4940,Orthodox,Psalter,150,4,Praise Him with the timbrel and dance; praise ...
4941,Orthodox,Psalter,150,5,Praise Him with the tuneful cymbals; praise Hi...

In [51]:
def word_count(text): 
    # splitting based on whitesapce
    words = text.split()
    # returning the number of words
    return len(words)

In [52]:
psalms['word_count'] = psalms['verse'].apply(word_count)

psalms

,tradition,text,psalm_num,verse_num,verse,word_count
0,Orthodox,Bible,1,1,Blessed is the man Who walks not in the counse...,28
1,Orthodox,Bible,1,2,But his will is in the law of the Lord And in ...,19
2,Orthodox,Bible,1,3,He shall be like a tree Planted by streams of ...,30
3,Orthodox,Bible,1,4,Not so are the ungodly not so But they are lik...,22
4,Orthodox,Bible,1,5,Therefore the ungodly shall not rise in the ju...,17
...,...,...,...,...,...,...
4937,Orthodox,Psalter,150,1,Praise God in His holy ones; praise Him in the...,14
4938,Orthodox,Psalter,150,2,Praise Him for His mighty acts; praise Him acc...,15
4939,Orthodox,Psalter,150,3,Praise Him with the sound of the trumpet; prai...,15
4940,Orthodox,Psalter,150,4,Praise Him with the timbrel and dance; praise ...,14
4941,Orthodox,Psalter,150,5,Praise Him with the tuneful cymbals; praise Hi...,20

In [53]:
# Calculate character count for each verse
psalms['char_count'] = psalms['verse'].apply(len)
psalms

,tradition,text,psalm_num,verse_num,verse,word_count,char_count
0,Orthodox,Bible,1,1,Blessed is the man Who walks not in the counse...,28,135
1,Orthodox,Bible,1,2,But his will is in the law of the Lord And in ...,19,80
2,Orthodox,Bible,1,3,He shall be like a tree Planted by streams of ...,30,155
3,Orthodox,Bible,1,4,Not so are the ungodly not so But they are lik...,22,99
4,Orthodox,Bible,1,5,Therefore the ungodly shall not rise in the ju...,17,96
...,...,...,...,...,...,...,...
4937,Orthodox,Psalter,150,1,Praise God in His holy ones; praise Him in the...,14,70
4938,Orthodox,Psalter,150,2,Praise Him for His mighty acts; praise Him acc...,15,87
4939,Orthodox,Psalter,150,3,Praise Him with the sound of the trumpet; prai...,15,80
4940,Orthodox,Psalter,150,4,Praise Him with the timbrel and dance; praise ...,14,76
4941,Orthodox,Psalter,150,5,Praise Him with the tuneful cymbals; praise Hi...,20,121

In [54]:
psalms.columns

Index(['tradition', 'text', 'psalm_num', 'verse_num', 'verse', 'word_count',
       'char_count'],
      dtype='object')

## Per Psalm

### Average Number of Verses

In [71]:

# Calculate total word count for each Psalm
total_word_count_per_psalm = psalms.groupby('text')['word_count'].sum().reset_index()

# Calculate the average word count for all Psalms
average_word_count = total_word_count_per_psalm['word_count'].mean()

# Display the results
print(total_word_count_per_psalm)
print(f"Average word count for all Psalms: {average_word_count:.2f}")

      text  word_count
0    Bible       43468
1  Psalter       43738
Average word count for all Psalms: 43603.00

### Psalm Word Count per Psalm

In [76]:

# Calculate the average word count per Psalm
average_word_count_per_psalm = psalms.groupby(['text', 'psalm_num'])['word_count'].sum().reset_index()
average_word_count_per_psalm

        text  psalm_num  word_count
0      Bible          1         133
1      Bible          2         199
2      Bible          3         150
3      Bible          4         165
4      Bible          5         248
..       ...        ...         ...
296  Psalter        146         164
297  Psalter        147         126
298  Psalter        148         207
299  Psalter        149         137
300  Psalter        150          78

[301 rows x 3 columns]

In [81]:
average_word_count_per_psalm['word_count'].mean()

289.72093023255815

In [83]:

# Calculate total word count for each Psalm
average_word_count_per_psalm = psalms.groupby(['text', 'psalm_num'])['word_count'].sum().reset_index()

# Calculate the average word count across all Psalms
overall_average_word_count = average_word_count_per_psalm['word_count'].mean()

# Display the DataFrame and the average
print(average_word_count_per_psalm)
print(f"Overall Average Word Count per Psalm: {overall_average_word_count:.0f}")

        text  psalm_num  word_count
0      Bible          1         133
1      Bible          2         199
2      Bible          3         150
3      Bible          4         165
4      Bible          5         248
..       ...        ...         ...
296  Psalter        146         164
297  Psalter        147         126
298  Psalter        148         207
299  Psalter        149         137
300  Psalter        150          78

[301 rows x 3 columns]
Overall Average Word Count per Psalm: 290

### Psalm Character Count 
#### Per Psalm

In [84]:

# Calculate the average word count per Psalm
average_word_count_per_psalm = psalms.groupby(['text', 'psalm_num'])['char_count'].sum().reset_index()
average_word_count_per_psalm

        text  psalm_num  char_count
0      Bible          1         648
1      Bible          2        1009
2      Bible          3         699
3      Bible          4         777
4      Bible          5        1240
..       ...        ...         ...
296  Psalter        146         874
297  Psalter        147         681
298  Psalter        148        1078
299  Psalter        149         732
300  Psalter        150         434

[301 rows x 3 columns]

In [81]:
average_word_count_per_psalm['word_count'].mean()

289.72093023255815

In [85]:

# Calculate total word count for each Psalm
average_word_count_per_psalm = psalms.groupby(['text', 'psalm_num'])['char_count'].sum().reset_index()

# Calculate the average word count across all Psalms
overall_average_char_count = average_word_count_per_psalm['char_count'].mean()

# Display the DataFrame and the average
print(average_word_count_per_psalm)
print(f"Overall Average Character Count per Psalm: {overall_average_char_count:.0f}")

        text  psalm_num  char_count
0      Bible          1         648
1      Bible          2        1009
2      Bible          3         699
3      Bible          4         777
4      Bible          5        1240
..       ...        ...         ...
296  Psalter        146         874
297  Psalter        147         681
298  Psalter        148        1078
299  Psalter        149         732
300  Psalter        150         434

[301 rows x 3 columns]
Overall Average Character Count per Psalm: 1475

#### Per Verse

In [86]:

# Calculate total character count for each verse
total_char_count_per_verse = psalms.groupby(['text', 'psalm_num', 'verse_num'])['char_count'].sum().reset_index()

# Calculate the average character count across all verses
overall_average_char_count = total_char_count_per_verse['char_count'].mean()

# Display the DataFrame and the average
print(total_char_count_per_verse)
print(f"Overall Average Character Count per Verse: {overall_average_char_count:.0f}")

         text  psalm_num  verse_num  char_count
0       Bible          1          1         135
1       Bible          1          2          80
2       Bible          1          3         155
3       Bible          1          4          99
4       Bible          1          5          96
...       ...        ...        ...         ...
4932  Psalter        150          1          70
4933  Psalter        150          2          87
4934  Psalter        150          3          80
4935  Psalter        150          4          76
4936  Psalter        150          5         121

[4937 rows x 4 columns]
Overall Average Character Count per Verse: 90

## Average Word Count Per Verse

In [72]:

# Calculate total word count for each Psalm
total_word_count_per_psalm = psalms.groupby('text')['word_count'].sum().reset_index()

# Calculate the average word count for all Psalms
average_word_count = total_word_count_per_psalm['word_count'].mean()

# Display the results
print(total_word_count_per_psalm)
print(f"Average word count for all Psalms: {average_word_count:.2f}")

      text  word_count
0    Bible       43468
1  Psalter       43738
Average word count for all Psalms: 43603.00

### Average Word Count

In [62]:
# Create a pivot table to find the average word count and character count per verse
pivot_table = pd.pivot_table(
    psalms,
    index=['text', 'psalm_num', 'verse_num'],  # Grouping by text, psalm number, and verse number
    values=['word_count', 'char_count'],        # Values we want to average
    aggfunc='mean'                              # Using mean to get the average
)
# Calculate averages
average_word_count = pivot_table['word_count'].mean()
average_char_count = pivot_table['char_count'].mean()

# Print formatted output
print(f"Average Word Count: {average_word_count:.0f}")
print(f"Average Character Count: {average_char_count:.0f}")

Average Word Count: 18
Average Character Count: 90